version: '3.8'

services:
    bot:
        container_name: tg-manga-caption-bot-deno
        build:
            context: .
            dockerfile: Dockerfile
        stop_signal: SIGINT
        restart: on-failure
        env_file: .env
        logging:
            options:
                max-size: 5m
        
        
