query ($id: Int, $search: String) { 

  Page(page:0, perPage:1) { 
    media(id: $id, search: $search, type: MANGA) {
      id
      title {
        romaji,
        english
      }
      coverImage {
        extraLarge
      }
      synonyms
      genres
      siteUrl
      countryOfOrigin
    }
  }
}
