query ($id: Int, $search: String, $page: Int) { 

  Page(page:$page, perPage:15) { 
    pageInfo {
      hasNextPage
      currentPage
    }
    media(id: $id, search: $search, type: MANGA) {
      id
      title {
        romaji,
        english
      }
      coverImage {
        medium
      }
      synonyms
      siteUrl
      format
    }
  }
}